Dataset: https://www.kaggle.com/datasets/itachi9604/disease-symptom-description-dataset

In [1]:
import seaborn as sns
from matplotlib import pyplot as plt
from sklearn import datasets
from sklearn.tree import DecisionTreeClassifier 
from sklearn import tree
import pandas as pd
import dtreeviz

In [2]:
# load the diseases -dataset
df = pd.read_csv("diseases.csv")

In [3]:
df.describe()

,Disease,Symptom_1,Symptom_2,Symptom_3,Symptom_4,Symptom_5,Symptom_6,Symptom_7,Symptom_8,Symptom_9,Symptom_10,Symptom_11,Symptom_12,Symptom_13,Symptom_14,Symptom_15,Symptom_16,Symptom_17
count,4920,4920,4920,4920,4572,3714,2934,2268,1944,1692,1512,1194,744,504,306,240,192,72
unique,41,34,48,54,50,38,32,26,21,22,21,18,11,8,4,3,3,1
top,Fungal infection,vomiting,vomiting,fatigue,high_fever,headache,nausea,abdominal_pain,abdominal_pain,yellowing_of_eyes,yellowing_of_eyes,irritability,malaise,muscle_pain,chest_pain,chest_pain,blood_in_sputum,muscle_pain
freq,120,822,870,726,378,348,390,264,276,228,198,120,126,72,96,144,72,72

In [4]:
# check duplicates
df.duplicated().sum()

4616

In [5]:
# remove duplicates
df.drop_duplicates(inplace=True)

In [6]:
# check nan values
df.isna().sum()

Disease         0
Symptom_1       0
Symptom_2       0
Symptom_3       0
Symptom_4      32
Symptom_5      70
Symptom_6     118
Symptom_7     146
Symptom_8     164
Symptom_9     184
Symptom_10    194
Symptom_11    236
Symptom_12    257
Symptom_13    274
Symptom_14    285
Symptom_15    286
Symptom_16    294
Symptom_17    303
dtype: int64

In [7]:
# remove nan values
df.dropna(inplace=True)

In [8]:
df.describe()

,Disease,Symptom_1,Symptom_2,Symptom_3,Symptom_4,Symptom_5,Symptom_6,Symptom_7,Symptom_8,Symptom_9,Symptom_10,Symptom_11,Symptom_12,Symptom_13,Symptom_14,Symptom_15,Symptom_16,Symptom_17
count,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
unique,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
top,Common Cold,continuous_sneezing,chills,fatigue,cough,high_fever,headache,swelled_lymph_nodes,malaise,phlegm,throat_irritation,redness_of_eyes,sinus_pressure,runny_nose,congestion,chest_pain,loss_of_smell,muscle_pain
freq,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1

In [9]:
df.head()

,Disease,Symptom_1,Symptom_2,Symptom_3,Symptom_4,Symptom_5,Symptom_6,Symptom_7,Symptom_8,Symptom_9,Symptom_10,Symptom_11,Symptom_12,Symptom_13,Symptom_14,Symptom_15,Symptom_16,Symptom_17
260,Common Cold,continuous_sneezing,chills,fatigue,cough,high_fever,headache,swelled_lymph_nodes,malaise,phlegm,throat_irritation,redness_of_eyes,sinus_pressure,runny_nose,congestion,chest_pain,loss_of_smell,muscle_pain

In [10]:
# not all data is numeric
# use LabelEncoder to make it numeric
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
variables = ['Symptom_1', 'Symptom_2', 'Symptom_3', 'Symptom_4', 'Symptom_5', 'Symptom_6',
             'Symptom_7', 'Symptom_8', 'Symptom_9', 'Symptom_10', 'Symptom_11', 'Symptom_12',
             'Symptom_13', 'Symptom_14', 'Symptom_15', 'Symptom_16', 'Symptom_17']
encoder = LabelEncoder()
df[variables] = df[variables].apply(encoder.fit_transform)

In [11]:
df.head()

,Disease,Symptom_1,Symptom_2,Symptom_3,Symptom_4,Symptom_5,Symptom_6,Symptom_7,Symptom_8,Symptom_9,Symptom_10,Symptom_11,Symptom_12,Symptom_13,Symptom_14,Symptom_15,Symptom_16,Symptom_17
260,Common Cold,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [12]:
original_categories = encoder.classes_
print("Original categories:", original_categories)

Original categories: [' muscle_pain']

In [13]:
X = df.drop('Disease', axis=1)
y = df['Disease']

In [14]:
# Fit the decision tree classifier with default hyper-parameters
clf = DecisionTreeClassifier()
model = clf.fit(X, y)

In [15]:
# pip install dtreeviz
import dtreeviz
viz_model = dtreeviz.model(clf,
                           X_train=X, y_train=y,
                           feature_names=X.columns,
                           target_name='Decision',
                           class_names=["No", "Yes"])

# for viewing in the Jupyter notebook
# Note: this is not practical with large 
# decision trees!
# adjust the scale if you need a bigger picture (for example 2.5)
viz_model.view(scale=1.5).save("dt_titanic_test.svg")

ValueError: y_train needs to consist only of numerical values. could not convert string to float: 'Common Cold'